# Generated by Django 4.0.3 on 2022-04-15 12:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('predict', '0003_universaltable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='atrybut',
            options={'verbose_name_plural': '02 Atrybut'},
        ),
        migrations.AlterModelOptions(
            name='klasa',
            options={'verbose_name_plural': '03 Klasa'},
        ),
        migrations.RemoveField(
            model_name='klasa',
            name='id_zbior',
        ),
        migrations.AddField(
            model_name='obserwacja',
            name='id_klasa',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='predict.klasa'),
        ),
    ]
